# Generated by Django 4.0.4 on 2022-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('body', models.TextField(verbose_name='body')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date')),
            ],
        ),
    ]
