# Generated by Django 4.0.4 on 2022-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='art_name',
            field=models.TextField(default=1, verbose_name='art_name'),
            preserve_default=False,
        ),
    ]
