# Generated by Django 4.0.4 on 2022-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_name_article_art_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.IntegerField(default=1, verbose_name='chapter'),
            preserve_default=False,
        ),
    ]
